### ISSUE TITLE
Identity provider integration

### ISSUE THREAD

**Issue by parkan** [mediachain/concat#14]
-  Dummy endpoint? -- edit: unnecessary (vyzo).
- [X] Blockstack/onename
- [X] Keybase

**Comment by vyzo** [comment]
cc @yusefnapora

**Comment by yusefnapora** [comment]
I'm leaning towards implementing keybase first, since it's easier to work with and has nice client libs and documentation.  But we should be aiming for a modular wrapper api that can use either, or our dummy implementation for testing, etc.

**Comment by parkan** [comment]
Yeah this should def be super modular and start with an impl that reads from a text file or something like that

**Comment by parkan** [comment]
What's our latest thinking here?

**Comment by vyzo** [comment]
I think we should punt on this (and general directory work), as the datastore and secondary indexes are higher priority.

**Comment by parkan** [comment]
Agreed, moving to V4

**Comment by parkan** [comment]
Prioritizing blockstack, let's see if we can get this into 1.2?

**Comment by vyzo** [comment]
I think this is a big issue that shouldn't be rushed, so v1.2 is probably unreasonable.

**Comment by vyzo** [comment]
I think a practical first step is to integrate with Blockstack identities through application specific keys.
This also extends to any provider which supports application specific keys.

In order to use applicaiton specific keys, we will have to generate them.
Thus, the user acquires a mediachain identity, which is a node-independent Ed25519 key.
The key is stored encrypted (as it is more valuable cryptographic material than node keys), and the marshalled public key is the application specific key registered in blockstack (eg through the onename app key interface)

For each node (concat or aleph) the user controls, we use the mediachain id to sign a node manifest, which includes the peer id together with the publisher id (and perhaps an associated signature for the publisher id, as in contrast to the peer id it can't be validated by virture of net connectivity).
This manifest associates the peer/publisher with an entity, specified as a blockstac id (we can use a prefix for specifying the provider).

The manifest is then provided by the node through the id protocol (with a request extension), and is also published to the directory when the node goes public.
This allows the directory to answer queries by entity id, and take the first step towards moderated directory domains; cf #71

**Comment by parkan** [comment]
Do we want to allow multiple manifests per node? What about the case of e.g. soundcloud running a node that represents hundreds of thousands of users?

**Comment by vyzo** [comment]
There is no reason not to have multiple manifests, although I think we may want to separate in node and hosted publisher manifests.

**Comment by parkan** [comment]
What remains here? Probably need some nicer tooling for the end user

**Comment by vyzo** [comment]
Support manifests in mcnode/mcdir and mcclient.
For nicer tooling, we'll have to add support in aleph.

**Comment by denisnazarov** [comment]
What are the expected CLI commands?

Will there be commands for interacting with/querying by blockstack ID?
